name: 'Send Email Action (Node)'
description: 'Send email to list of recipients in workflow'
author: 'Agnaldo Cavaleiro'
branding:
    icon: mail
    color: orange
inputs:
    connect_smtp:
        description: ''
        required: true
    server_address:
        description: 'URL of SMTP server'
        required: true
    port:
        description: 'Server port'
        default: "25"
    secure:
        description: 'Server port'
    username:
        description: 'Auth username: Use secret'
        required: true
    password:
        description: 'Auth password: Use secret'
        required: true
    from:
        description: 'Sender email address'
        required: true
    to:
        description: 'Comma-separated recipient list'
        required: true
    subject:
        description: 'Email subject line'
        required: true
    body:
        description: 'Email body text'
        required: true
    ignore_cert:
        description: Allow unsigned/invalid certificates
        required: false     
runs:
    using: 'node12'
    main: 'index.js'