name: Envio de email de prueba
on:
    #     - main
    workflow_dispatch:
env:
    SERVE_PORT: 465
    TO : ''

jobs:
  Send-email:
    runs-on: ubuntu-latest
    steps:
 
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
           
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.SERVER_ADDRESS}}
          port: "465"
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: "github-Prueba"
          to: "a.cavaleiro.costa@accenture.com"
          subject: Plain body with connection_url
          body: |
            first line
            second line Correo enviado Gui
          