name: Envio de email de prueba
on:
    #     - main
    workflow_dispatch:

jobs:
  Send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Instalar dependencias desde package.json
        run: npm install --production

      - name: Send mail
        uses: ./
        with:
          connection_url: smtp+starttls://${{secrets.MAIL_USERNAME}}:${{secrets.MAIL_PASSWORD}}@${{secrets.SERVER_ADDRESS}}/
          # server_address: ${{secrets.SERVER_ADDRESS}}
          # port: "465"
          # username: ${{secrets.MAIL_USERNAME}}
          # password: ${{secrets.MAIL_PASSWORD}}
          from: "github-Prueba-Gui"
          to: "a.cavaleiro.costa@accenture.com"
          subject: Multipart body (Markdown)
          body: file://src/body.txt
          convert_markdown: true
